### PR TITLE
added expecation that ab tests get scoped to urls

### PR DESCRIPTION
**Pull request by wheresrhys**
@matthew-andrews @tom-parker @GlynnPhillips 

A rehash of the earlier PR, but now ammit doesn't do the scoping - it's done in preflight to avoid diluting the ammit cache https://github.com/Financial-Times/next-preflight/pull/100

I'll create a test flag to verify it works before adding this info to existing ab tests and merging this

### CODE REVIEW

**Comment by tom-parker** [comment]
What is the extent of the cache dilution we're trying to avoid? I guess it's max number of running tests multiplied by the variants?

We'll need to make sure Spoor gets updated before we make these changes otherwise we'll have segmentation of events when the user wasn't actually allocated.

**Comment by wheresrhys** [comment]
Yep, it's tests * variants

> We'll need to make sure Spoor gets updated before we make these changes otherwise we'll have segmentation of events when the user wasn't actually allocated.

I was thinking about this, and I don't think this is an issue: Say a test only affects the home page, but we want to measure RFV, then we still want all tracking events across the site to be allocated, but just don't need every page on the site to be varied.

**Comment by tom-parker** [comment]
Ok makes sense I think

**Comment by commuterjoy** [comment]
Would it be sensible to scope it to application names?

**Comment by wheresrhys** [comment]
I might add that if there's demand, but it adds complexity (need to integrate preflight with service registry) and I think per url scoping is more flexible

**Pull request merged**
