### PR TITLE
Sends correct status code for validation

### PR DESCRIPTION
**Pull request by GlynnPhillips**
When this was removed it meant validation errors were being sent as
`500` and this meant it was picked up in vcl and sent with a generic "flags
is down" body.

Adds a test to make sure validation errors are sent correctly in the
future.

@adambraimbridge @tom-parker

### CODE REVIEW

**Comment by tom-parker** [comment]
👍

**Comment by adambraimbridge** [comment]
Unfortunately this has reverted the original bug I fixed in https://github.com/Financial-Times/next-flags-api/pull/49. 

We shouldn't let builds pass if they throw unexpected or incorrect errors (of course). My assertion is that the `Error: Can't set headers after they are sent` error is incorrect.   

image

@GlynnPhillips @tom-parker thoughts?

**Comment by GlynnPhillips** [comment]
Hey @adambraimbridge, Sorry you were in a meeting when I discovered why this is happening and completely forgot to fill you in after.

This error is due to [n-raven](https://github.com/Financial-Times/n-raven/blob/master/main.js#L28). On production stuff is sent to Sentry but when running locally it just sends the response, you can see that happening [here](https://github.com/Financial-Times/n-raven/blob/master/main.js#L28). So if anywhere should be changed I think it should be within `n-raven`. Maybe some more discussion is required though to decide how.

**Comment by adambraimbridge** [comment]
Thanks @GlynnPhillips. Yeah, definitely worth discussing this at some point.

**Pull request merged**
